### ISSUE TITLE
Hello. About keras version

### ISSUE THREAD

**Issue by shamangary** [antoine77340/LOUPE#5]
Hello. This is a very useful project. Do you mind if I rewrite the code and adapt LOUPE to keras version instead?

**Comment by antoine77340** [comment]
Hi !
Thank you !
Yes sure please do it ! I guess it should not be too difficult to transcript it to keras.
Please do ask me if you have any implementation question.

**Comment by shamangary** [comment]
Hi. I have change them into keras.
https://github.com/shamangary/LOUPE_Keras
It is a straightforward adaptation, I will keep looking if there is any bug.
Thanks for your project again.

**Comment by antoine77340** [comment]
That's nice ! Thank you so much for that :D
